FROM tjhei/ubuntu14

MAINTAINER timo.heister@gmail.com

RUN sudo apt-get update && sudo apt-get -yq install \
  numdiff \
  wget \
  zile \
  git \
  python \
  python-scipy \
  python-numpy \
  python-matplotlib \
  texlive-latex-base \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  texlive-latex-extra \
  python3-numpy python3-scipy python3-matplotlib
