FROM tjhei/ubuntu14

MAINTAINER timo.heister@gmail.com

RUN sudo apt-get update && sudo apt-get -yq install \
  numdiff \
  python \
  python-scipy \
  python-numpy \
  python-matplotlib \
  texlive-latex-base

RUN sudo apt-get -yq install \
  wget \
  zile \
  texlive-fonts-recommended \
  texlive-latex-recommended \
  texlive-latex-extra

RUN sudo apt-get -yq install \
  git
